#Emulicious settings file
#Tue Dec 02 23:44:55 BRST 2025
Recent0=D\:\\GBDK\\_projects\\examples\\examples.gb
Scale=6.75
AudioSync=false
WindowEmuliciousWidth=1936
WindowEmuliciousY=-8
WindowEmuliciousX=-8
WindowEmuliciousHeight=1048
Update=2
FontSize=13
CodeFontSize=13
