#Emulicious settings file
#Mon Dec 08 00:26:54 BRST 2025
GameBoyColorErrorBreakpointMessage1=
OutlineWidth=268
GameBoyColorErrorBreakpointMessage0=
WindowMemoryEditorOpen=false
WindowEmuliciousWidth=1096
GameBoyColorErrorBreakpointSuspend20=true
WindowPaletteViewerY=352
GameBoyColorErrorBreakpointCondition48=
WindowPaletteViewerX=297
WindowMemoryEditorSelectedAddress=0
DebuggerMemorySelectedTab=CPU
GameBoyColorErrorBreakpointCondition9=
GameBoyColorErrorBreakpointCondition8=
GameBoyColorErrorBreakpointCondition7=
GameBoyColorErrorBreakpointCondition6=
GameBoyColorErrorBreakpointCondition5=
WindowPaletteViewerHeight=313
GameBoyColorErrorBreakpointCondition4=
WindowMemoryEditorY=241
GameBoyColorErrorBreakpointCondition3=
WindowMemoryEditorX=207
BankSwapAtPCBreakpointSuspend=true
GameBoyColorErrorBreakpointCondition2=
GameBoyColorErrorBreakpointCondition1=
WindowTilemapViewerY=193
DataExecutionBreakpointCondition=
GameBoyColorErrorBreakpointCondition0=
WindowTilemapViewerX=1201
WindowPaletteViewerWidth=485
GameBoyColorErrorBreakpointSuspend19=true
GameBoyColorErrorBreakpointSuspend18=true
DataExecutionBreakpointEnabled=false
GameBoyColorErrorBreakpointSuspend17=true
GameBoyColorErrorBreakpointSuspend16=true
WindowDebuggerWidth=1483
GameBoyColorErrorBreakpointSuspend10=true
UninitializedMemoryBreakpointSuspend=true
WindowSpriteViewerOpen=false
DebuggerConsoleLogBreakpoints=true
WindowSpriteViewerHeight=527
GameBoyColorErrorBreakpointEnabled48=false
WindowMemoryEditorWidth=665
DebuggerHideCpuUsageGraph=false
DebuggerHideToolbar=false
WindowTilemapViewerOpen=false
GameBoyColorErrorBreakpointMessage48=
BankSwapAtPCBreakpointCondition=
Update=2
DebuggerSouthPanelSelectedTab=0
InterruptBreakpointEnabled=false
StackRomWriteBreakpointEnabled=false
StackWidth=1199
WindowPaletteViewerOpen=false
GameBoyColorErrorBreakpointCondition20=
GameBoyColorErrorBreakpointSuspend9=true
GameBoyColorErrorBreakpointSuspend8=true
GameBoyColorErrorBreakpointSuspend7=true
WindowSpriteViewerY=245
WindowSpriteViewerX=355
GameBoyColorErrorBreakpointSuspend6=true
GameBoyColorErrorBreakpointSuspend5=true
DataExecutionBreakpointSuspend=true
GameBoyColorErrorBreakpointSuspend4=true
GameBoyColorErrorBreakpointSuspend3=true
GameBoyColorErrorBreakpointSuspend2=true
GameBoyColorErrorBreakpointSuspend1=true
GameBoyColorErrorBreakpointSuspend0=true
UninitializedMemoryBreakpointCondition=
Recent3=D\:\\GBDK\\_projects\\examples\\examples.gb
WindowDebuggerOpen=false
SouthPanelHeight=635
Recent2=D\:\\GBDK\\gbdk\\examples\\gb\\sound\\sound.gb
GameBoyColorErrorBreakpointEnabled9=false
GameBoyColorErrorBreakpointEnabled8=false
WindowTilemapViewerWidth=439
Recent1=D\:\\GBDK\\_projects\\pacman\\Pacman.gb
GameBoyColorErrorBreakpointEnabled7=false
Recent0=D\:\\GBDK\\_projects\\pacman\\Pacman.gbc
GameBoyColorErrorBreakpointEnabled6=false
GameBoyColorErrorBreakpointEnabled5=false
GameBoyColorErrorBreakpointCondition19=
GameBoyColorErrorBreakpointEnabled4=false
GameBoyColorErrorBreakpointCondition18=
GameBoyColorErrorBreakpointEnabled3=false
GameBoyColorErrorBreakpointCondition17=
GameBoyColorErrorBreakpointEnabled2=false
GameBoyColorErrorBreakpointCondition16=
GameBoyColorErrorBreakpointEnabled1=false
GameBoyColorErrorBreakpointEnabled0=false
WindowMemoryEditorSelectedTab=CPU
GameBoyColorErrorBreakpointCondition10=
DebuggerWestPanelSelectedTab=0
AudioSync=false
WindowTilemapViewerHeight=625
InterruptBreakpointCondition=
GameBoyColorErrorBreakpointEnabled20=false
FontSize=13
StackSplitLocation=316
GameBoyColorErrorBreakpointMessage20=
WindowDebuggerHeight=977
GameBoyColorErrorBreakpointSuspend48=true
BankSwapAtPCBreakpointEnabled=false
CodeFontSize=13
DebuggerMemoryTabVisibleRect=0,0,625,198
InterruptBreakpointSuspend=true
StackRomWriteBreakpointSuspend=true
GameBoyColorErrorBreakpointEnabled19=false
GameBoyColorErrorBreakpointEnabled18=false
GameBoyColorErrorBreakpointEnabled17=false
WindowMemoryEditorTabVisibleRect=0,0,625,400
GameBoyColorErrorBreakpointEnabled16=false
StackRomWriteBreakpointCondition=
WindowEmuliciousHeight=1033
GameBoyColorErrorBreakpointMessage19=
WindowSpriteViewerWidth=370
GameBoyColorErrorBreakpointMessage18=
GameBoyColorErrorBreakpointMessage17=
GameBoyColorErrorBreakpointMessage16=
GameBoyColorErrorBreakpointEnabled10=true
GameBoyColorErrorBreakpointMessage10=
Scale=6.75
WindowDebuggerY=20
DebuggerEventFiltersGameBoyColor=
WindowDebuggerX=0
DebuggerMemorySelectedAddress=-1
UninitializedMemoryBreakpointEnabled=false
WindowEmuliciousY=0
WindowEmuliciousX=-8
GameBoyColorErrorBreakpointMessage9=
GameBoyColorErrorBreakpointMessage8=
GameBoyColorErrorBreakpointMessage7=
WindowMemoryEditorHeight=534
GameBoyColorErrorBreakpointMessage6=
GameBoyColorErrorBreakpointMessage5=
GameBoyColorErrorBreakpointMessage4=
GameBoyColorErrorBreakpointMessage3=
GameBoyColorErrorBreakpointMessage2=
