#Emulicious settings file
#Sat Dec 06 20:45:15 BRST 2025
Recent0=D\:\\GBDK\\gbdk\\examples\\gb\\sound\\sound.gb
Scale=6.75
AudioSync=false
WindowEmuliciousWidth=1096
WindowEmuliciousY=-8
WindowEmuliciousX=-8
WindowEmuliciousHeight=1033
Update=2
FontSize=13
CodeFontSize=13
Recent1=D\:\\GBDK\\_projects\\examples\\examples.gb
